lojas/urls.py
from django.urls import path
from . import views

app_name = 'loja'


urlpatterns = [
    path('', views.Lojas.as_view(), name='lojas'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('cadastro/', views.Cadastro.as_view(), name='cadastro'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('perfil/', views.ShowPerfil.as_view(), name='perfil'),
    path('perfil/endereco', views.AddEndereco.as_view(), name='add_endereco')
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sabores.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('lojas/', include('lojas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/models.py
from django.core.exceptions import ValidationError
from utils.validacpf import valida_cpf
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idade = models.PositiveIntegerField()
    cpf = models.CharField(max_length=14, unique=True)

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'

    def clean(self) -> None:
        error_msg = {}

        if not valida_cpf(self.cpf):
            error_msg['cpf'] = 'CPF invalido'

        if self.idade:
            if self.idade < 18 or self.idade > 120:
                error_msg['idade'] = 'Idade Inválida'

        if error_msg:
            raise ValidationError(error_msg)


class Endereco(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    rua = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    complemento = models.CharField(max_length=255)
    numero = models.CharField(max_length=5)
    estado = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f'{self.rua}, n {self.numero}, {self.cidade}'

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class EnderecoForm(forms.ModelForm):
    class Meta:
        model = models.Endereco
        fields = '__all__'
        exclude = ('perfil',)


class PerfilForm(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields = '__all__'
        exclude = ('user',)


class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Senha:'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Confirmar Senha'
    )

    username = forms.CharField(
        widget=forms.TextInput(),
        label='Usuário',
    )

    first_name = forms.CharField(
        widget=forms.TextInput(),
        label='Nome',
        required=True
    )

    last_name = forms.CharField(
        widget=forms.TextInput(),
        label='Sobrenome',
        required=True
    )

    email = forms.CharField(
        widget=forms.EmailInput(),
        label='Email',
        required=True
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'password', 'password2', 'email')

    def clean(self, *args, **kwargs):
        data = self.cleaned_data

        validation_error_messages = {}

        usuario_data = data.get('username')
        email_data = data.get('email')
        password_data = data.get('password')
        password2_data = data.get('password2')

        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()

        erros_msg_user_exists = 'Usuário já existe'
        erros_msg_email_exists = 'Email já existe'
        erros_msg_password_match = 'As duas senhas não conferem'
        erros_msg_password_short = 'Sua senha precisa ter no mínimo 6 '\
            'carácteres'

        if usuario_db:
            validation_error_messages['username'] = erros_msg_user_exists

        if email_db:
            validation_error_messages['email'] = erros_msg_email_exists

        if len(str(password_data)) < 6:
            validation_error_messages['password'] = erros_msg_password_short

        if not password_data == password2_data:
            validation_error_messages['password'] = erros_msg_password_match

        if validation_error_messages:
            raise forms.ValidationError(validation_error_messages)

        return super().clean()

perfil/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.views import View
from . import forms, models
from django.contrib import messages


class BaseView(View):
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.contexto = {
            'userform': forms.UserForm(data=self.request.POST or None),
            'enderecoform': forms.EnderecoForm(data=self.request.POST or None),
            'perfilform': forms.PerfilForm(data=self.request.POST or None),
        }

        self.userform = self.contexto['userform']
        self.enderecoform = self.contexto['enderecoform']
        self.perfilform = self.contexto['perfilform']

        self.renderizar = render(
            self.request, 'perfil/cadastro.html', self.contexto)

    def is_all_valid(self):
        return (self.userform.is_valid() and self.enderecoform.is_valid() and
                self.perfilform.is_valid())

    def get(self, *args, **kwargs):
        return self.renderizar


class Login(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'perfil/login.html')

    def post(self, *args, **kwargs):

        usuario = self.request.POST.get('usuario')
        senha = self.request.POST.get('password')

        autenticacao = authenticate(
            self.request, username=usuario, password=senha)

        if not autenticacao:
            messages.error(
                self.request,
                'Usuário e/ou senha inválidos'
            )
            return render(self.request, 'perfil/login.html')

        login(self.request, user=autenticacao)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}

        messages.success(
            self.request,
            'Login feito com sucesso'
        )

        return redirect('sabores:introducao')


class Logout(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        messages.success(
            self.request,
            'Logout realizado com sucesso.'
        )
        return redirect('sabores:introducao')


class ShowPerfil(BaseView):
    def get(self, *args, **kwargs):

        user = self.request.user
        perfil: models.Perfil = models.Perfil.objects.filter(
            user=user.id).first()

        contexto = {
            'user': user,
            'perfil': perfil,
        }

        return render(self.request, 'perfil/showperfil.html', contexto)


class Cadastro(BaseView):
    def post(self, *args, **kwargs):
        if not self.is_all_valid():
            messages.error(
                self.request,
                'Formulário preenchido incorretamente'
            )
            return self.renderizar

        password = self.userform.cleaned_data.get('password')

        usuario = self.userform.save(commit=False)
        usuario.set_password(password)
        usuario.save()

        perfil = self.perfilform.save(commit=False)
        perfil.user = usuario
        perfil.save()

        endereco = self.enderecoform.save(commit=False)
        endereco.perfil = perfil
        endereco.save()

        messages.success(
            self.request,
            'Cadastro efetuado com sucesso.'
        )

        return redirect('perfil:login')


class AddEndereco(ShowPerfil):
    def get(self, *args, **kwargs):
        return render(self.request, 'perfil/add_endereco.html', self.contexto)

    def post(self, *args, **kwargs):
        if not self.enderecoform.is_valid():
            return render(self.request, 'perfil/add_endereco.html',
                          self.contexto)

        perfil: models.Perfil = models.Perfil.objects.filter(
            user=self.request.user.id).first()

        endereco = self.enderecoform.save(commit=False)
        endereco.perfil = perfil
        endereco.save()

        messages.success(
            self.request,
            'Endereço adicionado com sucesso.'
        )

        return redirect('perfil:perfil')

perfil/templates/perfil/add_endereco.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Meu Perfil{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Adicionar Endereco</h2>

        <form action="#" method="POST" class="login-form">
            {% csrf_token %}
            {{ enderecoform|crispy }}
            <input class="submit-button" type="submit" value="Adicionar">

        </form>

    </section>

</main>

{% endblock %}

perfil/templates/perfil/cadastro.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Cadastre-se{% endblock %}

{% block content %}

<main>
    <section class="main-section">
        <h2 class="main-section-title">Cadastro</h2>

        <form action="#" method="POST" class="login-form">
            {% csrf_token %}
            {{ userform|crispy }}
            {{ perfilform|crispy }}
            {{ enderecoform|crispy }}
            <input class="submit-button" type="submit" value="Cadastre-se">
        </form>
    </section>
</main>

{% endblock %}

perfil/templates/perfil/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Login</h2>

        <form action="#" method="POST" class="login-form">
            {% csrf_token %}
            <label for="usuario">Usuario:</label>
            <input type="text" id="usuario" name="usuario">

            <label for="password">Senha:</label>
            <input type="password" id="password" name="password">

            <div class="row">
                <a href="{% url 'perfil:cadastro' %}" class="submit-button col col-pizza">Cadastre-se</a>
                <input class="submit-button col col-pizza" type="submit" value="Login">
            </div>
        </form>
    </section>
</main>
{% endblock %}

perfil/templates/perfil/showperfil.html
{% extends 'base.html' %}

{% block title %}Meu Perfil{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Meu Perfil</h2>

        <form action="#" method="POST" class="login-form">
            {% csrf_token %}
            <div class="row">
                <div class="col col-pizza">
                    <label for="user">User:</label>
                    <input class="read" type="text" id="user" name="user" value="{{ user }}" readonly>

                    <label for="name">Nome:</label>
                    <input class="read" type="text" id="name" name="name" value="{{ user.first_name }}" readonly>

                    <label for="idade">Idade:</label>
                    <input class="read" type="text" id="idade" name="idade" value="{{ perfil.idade }}" readonly>
                </div>
                <div class="col col-pizza">
                    <label for="email">Email:</label>
                    <input class="read" type="email" id="email" name="email" value="{{ user.email }}" readonly>

                    <label for="sobrenome">Sobrenome:</label>
                    <input class="read" type="text" id="sobrenome" name="sobrenome" value="{{ user.last_name }}"
                        readonly>

                    <label for="cpf">CPF:</label>
                    <input class="read" type="text" id="cpf" name="cpf" value="{{ perfil.cpf }}" readonly>
                </div>
            </div>
        </form>

    </section>
    <section class="stores main-section">
        <h2 class="main-section-title">Meus Endereços.</h2>

        <div class="row">
            {% for endereco in perfil.endereco_set.all %}
            <div class="col col1-3">
                <address>
                    <p>
                        <span class="hidden">Endereço</span>
                        Rua {{ endereco.rua }}, número {{ endereco.numero }}, {{ endereco.complemento }}
                    </p>

                    <p>
                        {{ endereco.cidade }}, {{ endereco.estado }}
                    </p>
                </address>
            </div>
            {% endfor %}
        </div>

        <a class="submit-button" href="{% url 'perfil:add_endereco' %}">Adicionar Endereço</a>

    </section>

</main>

{% endblock %}