lojas/urls.py
from django.urls import path
from . import views

app_name = 'loja'


urlpatterns = [
    path('', views.Lojas.as_view(), name='lojas'),
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('', views.Carrinho.as_view(), name='carrinho'),
    path('fazerpedido/', views.FazerPedido.as_view(), name='fazerpedido'),
    path('meuspedidos/', views.MeusPedidos.as_view(), name='meuspedidos'),
    path('removerdocarrinho/', views.RemoveCarrinho.as_view(),
         name='removerdocarrinho'),
    path('confirmarpedido/', views.ConfirmarPedido.as_view(),
         name='confirmarpedido')
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('cadastro/', views.Cadastro.as_view(), name='cadastro'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('perfil/', views.ShowPerfil.as_view(), name='perfil'),
    path('perfil/endereco', views.AddEndereco.as_view(), name='add_endereco')
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sabores.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('lojas/', include('lojas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sabores/urls.py
from django.urls import path
from . import views

app_name = 'sabores'


urlpatterns = [
    path('', views.Introducao.as_view(), name='introducao'),
    path('cardapio/', views.Cardapio.as_view(), name='cardapio'),
]

templates/parciais/_footer.html
<footer class="main-footer">
    <p>&copy; from my mind.</p>
</footer>

templates/parciais/_head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://kit.fontawesome.com/18a89ba9ae.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'css/style.css'%}">

templates/parciais/_messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} main-section">
    {{ message }}
</div>
{% endfor %}
{% endif %}

templates/parciais/_nav.html
<header class="main-header row">
    <h1 class="main-header-logo col col1-3"><a href="{% url 'sabores:introducao' %}" class="logo"><i
                class="fas fa-pizza-slice"></i>Pizza's</a>
    </h1>
    <nav class="main-header-nav col col2-3">
        <ul>
            {% if not request.user.is_authenticated %}
            <li><a href="{% url 'sabores:cardapio' %}">Cardápio</a></li>
            <li><a href="{% url 'loja:lojas' %}">Lojas</a></li>
            <li><a href="{% url 'perfil:login' %}">Fazer Login</a></li>
            <li><a href="{% url 'perfil:cadastro' %}">Cadastre-se</a></li>
            <li><a href="{% url 'pedido:carrinho' %}"><i class="fas fa-shopping-cart"></i> Carrinho</a></li>
            {% else %}
            <li><a href="{% url 'sabores:cardapio' %}">Cardápio</a></li>
            <li><a href="{% url 'loja:lojas' %}">Lojas</a></li>
            <li><a href="{% url 'pedido:meuspedidos' %}">Meus Pedidos</a></li>
            <li><a href="{% url 'perfil:perfil' %}">{{ request.user|title }}</a></li>
            <li><a href="{% url 'pedido:carrinho' %}"><i class="fas fa-shopping-cart"></i> Carrinho</a></li>
            <li><a href="{% url 'perfil:logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

<div class="header-space"></div>