lojas/urls.py
from django.urls import path
from . import views

app_name = 'loja'


urlpatterns = [
    path('', views.Lojas.as_view(), name='lojas'),
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('', views.Carrinho.as_view(), name='carrinho'),
    path('fazerpedido/', views.FazerPedido.as_view(), name='fazerpedido'),
    path('meuspedidos/', views.MeusPedidos.as_view(), name='meuspedidos'),
    path('removerdocarrinho/', views.RemoveCarrinho.as_view(),
         name='removerdocarrinho'),
    path('confirmarpedido/', views.ConfirmarPedido.as_view(),
         name='confirmarpedido')
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sabores.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('lojas/', include('lojas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sabores/urls.py
from django.urls import path
from . import views

app_name = 'sabores'


urlpatterns = [
    path('', views.Introducao.as_view(), name='introducao'),
    path('cardapio/', views.Cardapio.as_view(), name='cardapio'),
]

sabores/models.py
from django.conf import settings
import os
from PIL import Image
from django.db import models

# Create your models here.


class Sabor(models.Model):
    nome_sabor = models.CharField(
        max_length=100, unique=True, verbose_name='nome do sabor')
    descricao_sabor = models.CharField(
        max_length=100, verbose_name='descrição')
    preco_grande = models.FloatField()
    preco_medio = models.FloatField()
    preco_pequeno = models.FloatField()
    imagem = models.ImageField(upload_to='sabores/', blank=True, null=True)
    no_cardapio = models.BooleanField(
        default=True, verbose_name='Está no cardápio?')
    doce = models.BooleanField(default=False)
    salgado = models.BooleanField(default=False)

    @staticmethod
    def resize_img(img, new_width=800.0):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_img(self.imagem, max_image_size)

    def __str__(self):
        return self.nome_sabor

    class Meta:
        verbose_name = 'Sabor'
        verbose_name_plural = 'Sabores'

sabores/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from . import models


class Introducao(ListView):
    model = models.Sabor
    template_name = 'sabores/introducao.html'


class Cardapio(View):
    def get(self, *args, **kwargs):

        sabores_salgados = models.Sabor.objects.filter(
            no_cardapio=True, salgado=True)
        sabores_doce = models.Sabor.objects.filter(no_cardapio=True, doce=True)

        contexto = {
            'sabores_salgados': sabores_salgados,
            'sabores_doces': sabores_doce
        }

        return render(self.request, 'sabores/cardapio.html', contexto)

sabores/templates/sabores/cardapio.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cardapio{% endblock title %}

{% block content %}
<section class="main-section">
    <h2 class="main-section-title">Cardápio</h2>

    <h3 class="main-section-subtitle">Veja nossas deliciosas pizzas feitas com carinho pelos nossos chefes
        italianos.</h3>

    <div class="pizza-categories">
        <h4 class="pizza-categories-title">Salgados</h4>
    </div>

    {% for sabor_salgado in sabores_salgados %}
    <div class="cardapio-card">
        <a href="{% url 'pedido:fazerpedido' %}"><img src="{{ sabor_salgado.imagem.url }}"
                alt="Uma foto da nossa deliciosa pizza sabor {{ sabor_salgado.nome_sabor }}"></a>
        <h4>{{ sabor_salgado.nome_sabor }}</h4>
        <p>{{ sabor_salgado.descricao_sabor }}</p>
        <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peça já</a>
    </div>
    {% endfor %}

    <div class="pizza-categories pizza-categories-margin-top">
        <h4 class="pizza-categories-title">Doces</h4>
    </div>

    {% for sabor_doce in sabores_doces %}
    <div class="cardapio-card">
        <img src="{{ sabor_doce.imagem.url }}"
            alt="Uma foto da nossa deliciosa pizza sabor {{ sabor_doce.nome_sabor }}">
        <h4>{{ sabor_doce.nome_sabor }}</h4>
        <p>{{ sabor_doce.descricao_sabor }}</p>
        <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peça já</a>
    </div>
    {% endfor %}


</section>

{% endblock content %}

sabores/templates/sabores/introducao.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Pizzaria{% endblock title %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Venha pedir sua pizza conosco!</h2>

        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates magnam odit alias est reiciendis
            architecto quibusdam illo. Voluptatum explicabo, autem qui fuga, quasi laudantium sunt corporis quis
            unde quisquam cupiditate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid porro minus
            assumenda sunt corrupti maiores! Exercitationem beatae, quae alias atque, explicabo quibusdam modi velit
            consequuntur ut aspernatur hic. Sed, ipsum.</p>
    </section>

    <section class="main-section">
        <h2 class="main-section-title">Nossas Maravilhosas Pizzas!</h2>

        <div class="row">
            <div class="col col-pizza">
                <a href="{% url 'pedido:fazerpedido' %}" class="pizza-card">
                    <img src="{% static '/img/portuguese_pizza.jpg' %}"
                        alt="Uma foto da nossa deliciosa pizza sabor portuguesa">
                </a>
                <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peca já</a>

                <a href="{% url 'pedido:fazerpedido' %}" class="pizza-card">
                    <img src="{% static '/img/margherita_pizza.jpg' %}"
                        alt="Uma foto da nossa deliciosa pizza sabor margherita">
                </a>
                <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peca já</a>
            </div>
            <div class="col col-pizza">
                <a href="{% url 'pedido:fazerpedido' %}" class="pizza-card">
                    <img src="{% static '/img/pepperoni_pizza.jpg' %}"
                        alt="Uma foto da nossa deliciosa pizza sabor pepperoni">
                </a>
                <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peca já</a>

                <a href="{% url 'pedido:fazerpedido' %}" class="pizza-card">
                    <img src="{% static '/img/sweet_pizza.jpg' %}"
                        alt="Uma foto da nossa deliciosa pizza sabor chocolate branco com morango">
                </a>
                <a href="{% url 'pedido:fazerpedido' %}" class="ask-pizza">Peça já</a>
            </div>
        </div>
    </section>
</main>

{% endblock content %}