lojas/urls.py
from django.urls import path
from . import views

app_name = 'loja'


urlpatterns = [
    path('', views.Lojas.as_view(), name='lojas'),
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('', views.Carrinho.as_view(), name='carrinho'),
    path('fazerpedido/', views.FazerPedido.as_view(), name='fazerpedido'),
    path('meuspedidos/', views.MeusPedidos.as_view(), name='meuspedidos'),
    path('removerdocarrinho/', views.RemoveCarrinho.as_view(),
         name='removerdocarrinho'),
    path('confirmarpedido/', views.ConfirmarPedido.as_view(),
         name='confirmarpedido')
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sabores.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('lojas/', include('lojas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/models.py
from django.db import models
from perfil.models import Perfil
from datetime import datetime


class Pedido(models.Model):
    perfil_pedido = models.ForeignKey(
        Perfil, on_delete=models.CASCADE, verbose_name='Cliente')
    total = models.FloatField()
    endereco = models.CharField(max_length=255)
    status = models.CharField(
        max_length=2,
        default='P',
        choices=(('P', 'Preparando'), ('E', 'Enviado'), ('R', 'Recebido'))
    )
    data = models.DateTimeField(
        default=datetime.now())

    def __str__(self) -> str:
        return f'Pedido {self.id}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    sabor = models.CharField(max_length=100)
    tamanho = models.CharField(max_length=100)
    quantidade = models.IntegerField()
    preco = models.FloatField()

    def __str__(self) -> str:
        return self.sabor

pedido/views.py
from django.contrib.auth.models import User
from django.http.response import Http404
from perfil.models import Endereco, Perfil
from .models import ItemPedido, Pedido
from typing import Dict, List
from django.shortcuts import redirect, render
from django.views import View
from sabores import models
from django.contrib import messages


class Carrinho(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        carrinho: Dict = self.request.session.get('carrinho')
        total = ''

        if carrinho:
            total = self.get_total()

        contexto: Dict = {
            'carrinho': carrinho,
            'total': total
        }

        return render(self.request, 'pedido/carrinho.html', contexto)

    def get_total(self):
        return sum(
            [x['preco']
             if type(x) == dict
             else 0
             for x
             in list(self.request.session['carrinho'].values())
             ]
        )


class RemoveCarrinho(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        self.carrinho: Dict = self.request.session.get('carrinho')
        self.sabor: str = self.request.GET.get('vid')
        key = self.get_deleted_key()
        http_referer = self.request.META.get('HTTP_REFERER')

        if not self.carrinho or not self.sabor:
            return redirect('pedido:fazerpedido')

        try:
            del self.carrinho[key]
        except:
            raise Http404

        self.request.session.save()

        return redirect(http_referer)

    def get_deleted_key(self):
        keys: List = [
            k if v['sabor'] == self.sabor else None
            for k, v in self.carrinho.items()
        ]

        for key in keys:
            if key is not None:
                return key


class ConfirmarPedido(Carrinho):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        carrinho: Dict = self.request.session.get('carrinho')

        if not carrinho:
            return redirect('pedido:fazerpedido')

        user: User = self.request.user
        perfil: Perfil = Perfil.objects.filter(user=user.id).first()
        enderecos: Endereco = Endereco.objects.filter(perfil=perfil)
        total: float = self.get_total()

        contexto: Dict = {
            'carrinho': carrinho,
            'total': total,
            'enderecos': enderecos
        }

        return render(self.request, 'pedido/confirmar_pedido.html', contexto)

    def post(self, *args, **kwargs):
        user_id = self.request.user.id
        perfil: Perfil = Perfil.objects.filter(user=user_id).first()
        endereco_id: str = self.request.POST.get('endereco')
        endereco_db: Endereco = Endereco.objects.filter(id=endereco_id).first()
        endereco: str = f'{endereco_db.rua}, n {endereco_db.numero}, '\
            f'{endereco_db.cidade}'

        carrinho = self.request.session.get('carrinho')

        pedido: Pedido = Pedido(
            perfil_pedido=perfil,
            endereco=endereco,
            total=self.get_total(),
            status='P',
        )
        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    sabor=pizza['sabor'],
                    tamanho=pizza['tamanho'],
                    quantidade=pizza['quantidade'],
                    preco=pizza['preco'],
                )
                for pizza in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        messages.success(
            self.request,
            'Pedido realizado com sucesso. Agradecemos a preferência.'
        )
        return redirect('pedido:meuspedidos')


class MeusPedidos(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        user_id = self.request.user.id
        perfil: Perfil = Perfil.objects.filter(user=user_id).first()
        pedidos: Pedido = Pedido.objects.filter(
            perfil_pedido=perfil)

        contexto: Dict = {
            'pedidos': pedidos,
        }
        
        return render(self.request, 'pedido/meus_pedidos.html', contexto)


class FazerPedido(View):
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        sabores_salgados: models.Sabor = models.Sabor.objects.filter(
            no_cardapio=True, salgado=True)

        sabores_doces: models.Sabor = models.Sabor.objects.filter(
            no_cardapio=True, doce=True)

        self.contexto: Dict = {
            'sabores_salgados': sabores_salgados,
            'sabores_doces': sabores_doces,
        }

        self.renderizar = render(
            self.request, 'pedido/fazer_pedido.html', self.contexto)

    def get(self, *args, **kwargs):
        return self.renderizar

    def post(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        http_referer = self.request.META.get('HTTP_REFERER')
        datas: Dict = self.request.POST
        self.carrinho = self.request.session.get('carrinho')
        self.tamanho: str = datas.get('size')
        self.quantidade: int = 1
        sabores_id: List = []

        for k, v in datas.items():
            if 'sabor' in k:
                sabores_id.append(int(v))

        if not self.tamanho:
            messages.error(
                self.request,
                'Precisa selecionar um tamanho',
            )
            return redirect(http_referer)

        if self.is_2_flavors():
            if len(datas) != 4:
                messages.error(
                    self.request,
                    'Selecione 2 sabores'
                )
                return redirect(http_referer)

            self.sabor1 = models.Sabor.objects.filter(id=sabores_id[0]).first()
            self.sabor2 = models.Sabor.objects.filter(id=sabores_id[1]).first()
            self.sabor = f'{self.sabor1} e {self.sabor2}'
            self.sabor_id = str(sum(sabores_id)) + self.sabor2.nome_sabor

        if self.is_1_flavor():
            if len(datas) != 3:
                messages.error(
                    self.request,
                    'Selecione apenas 1 sabor'
                )
                return redirect(http_referer)
            self.sabor1 = models.Sabor.objects.filter(id=sabores_id[0]).first()
            self.sabor = f'{self.sabor1}'
            self.sabor_id = str(sum(sabores_id))

        if not self.carrinho:
            self.request.session['carrinho'] = {}
            self.carrinho = self.request.session['carrinho']

        if self.sabor_id in self.carrinho.keys():
            self.carrinho[self.sabor_id]['quantidade'] += 1

            preco = self.get_preco()

            self.carrinho[self.sabor_id]['preco'] = round(preco, 2)
        else:

            preco = self.get_preco()
            tamanho = self.get_size()

            self.carrinho[self.sabor_id] = {
                'sabor': self.sabor,
                'tamanho': tamanho,
                'quantidade': self.quantidade,
                'preco': round(preco, 2)
            }

        self.request.session.save()

        messages.success(
            self.request,
            'Pizza adicionada ao carrinho. Vá ate lá para finalizar o pedido.'
        )
        return redirect('pedido:fazerpedido')

    def get_preco(self):
        tamanho: str = self.tamanho
        quantidade: int = self.quantidade
        if self.sabor_id in self.carrinho:
            quantidade = self.carrinho[self.sabor_id]['quantidade']

        if 'grande' in tamanho:
            if self.is_1_flavor():
                preco = self.sabor1.preco_grande * quantidade

            if self.is_2_flavors():
                preco = ((self.sabor1.preco_grande +
                         self.sabor2.preco_grande) / 2 * quantidade)

        if 'media' in tamanho:
            if self.is_1_flavor():
                preco = self.sabor1.preco_medio * quantidade

            if self.is_2_flavors():
                preco = ((self.sabor1.preco_medio +
                         self.sabor2.preco_medio) / 2 * quantidade)

        if 'pequena' in tamanho:
            if self.is_1_flavor():
                preco = self.sabor1.preco_pequeno * quantidade

            if self.is_2_flavors():
                preco = ((self.sabor1.preco_pequeno +
                         self.sabor2.preco_pequeno) / 2 * quantidade)

        return preco

    def get_size(self):
        if 'grande' in self.tamanho:
            return 'Pizza Grande'

        if 'media' in self.tamanho:
            return 'Pizza Media'

        return 'Pizza Pequena'

    def is_2_flavors(self):
        return '2' in self.tamanho

    def is_1_flavor(self):
        return '1' in self.tamanho

pedido/templates/pedido/carrinho.html
{% extends 'base.html' %}
{% load myfilter %}

{% block title %}Carrinho{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Carrinho</h2>
        {% if carrinho %}

        <table class="car-table">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Sabores</th>
                    <th>Quantidade</th>
                    <th>Remover</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td>Total:</td>
                    <td colspan="4" style="text-align: right;">{{ total|money }}</td>
                </tr>
            </tfoot>
            <tbody>
                {% for item in carrinho.values %}
                <tr>
                    <td>{{ item.tamanho }}</td>
                    <td>{{ item.sabor }}</td>
                    <td>{{ item.quantidade }}</td>
                    <td><a href="{% url 'pedido:removerdocarrinho' %}?vid={{ item.sabor }}"><i
                                class="fas fa-minus-circle red-button"></i></a></td>
                    <td>{{ item.preco|money }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <a class="submit-button" href="{% url 'pedido:confirmarpedido' %}">Fazer Pedido</a>

        {% else %}
        <h3 class="main-section-subtitle">Carrinho Vazio.</h3>
        <p>Favor adicionar items ao carrinho.</p>
        {% endif %}
    </section>
</main>

{% endblock %}

pedido/templates/pedido/confirmar_pedido.html
{% extends 'base.html' %}
{% load myfilter %}

{% block title %}Confirmar Pedido{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Carrinho</h2>

        <table class="car-table">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Sabores</th>
                    <th>Quantidade</th>
                    <th>Remover</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td>Total:</td>
                    <td colspan="4" style="text-align: right;">{{ total|money }}</td>
                </tr>
            </tfoot>
            <tbody>
                {% for item in carrinho.values %}
                <tr>
                    <td>{{ item.tamanho }}</td>
                    <td>{{ item.sabor }}</td>
                    <td>{{ item.quantidade }}</td>
                    <td><a href="{% url 'pedido:removerdocarrinho' %}?vid={{ item.sabor }}"><i
                                class="fas fa-minus-circle red-button"></i></a></td>
                    <td>{{ item.preco|money }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2 class="main-section-title">Selecionar Endereço de Entrega</h2>

        <form action="#" method="POST">
            {% csrf_token %}

            <div class="row">
                {% for endereco in enderecos %}
                <div class="col col1-3 address-box">
                    <address>
                        <label for="endereco{{ endereco.id }}">
                            <span class="hidden">Endereço</span>
                            Rua {{ endereco.rua }}, número {{ endereco.numero }}
                        </label>

                        <p>
                            {{ endereco.cidade }}, {{ endereco.estado }}
                        </p>
                        <input type="radio" id="endereco{{ endereco.id }}" name="endereco" value="{{endereco.id}}">
                    </address>
                </div>
                {% endfor %}
            </div>

            <input class="submit-button" type="submit" value="Fazer Pedido">

        </form>

    </section>
</main>

{% endblock %}

pedido/templates/pedido/fazer_pedido.html
{% extends 'base.html' %}
{% load myfilter %}

{% block title %}Fazer Pedido{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Faça seu pedido</h2>


        <form action="#" class="pizza-form" method="POST">
            {% csrf_token %}
            <ul class="pizza-form-list">
                <li class="pizza-styles">
                    <i class="fas fa-pizza-slice"></i>Pizza Grande
                    <ul>
                        <li class="row">
                            <label class="col col1-3" for="pizza-grande-2">2 sabores</label>
                            <input class="col col1-3" type="radio" id="pizza-grande-2" name="size"
                                value="pizza-grande-2">
                        </li>
                        <li class="row">
                            <label class="col col1-3" for="pizza-grande-1">1 sabor</label>
                            <input class="col col1-3" type="radio" id="pizza-grande-1" name="size"
                                value="pizza-grande-1">
                        </li>
                    </ul>
                </li>
                <li class="pizza-styles">
                    <i class="fas fa-pizza-slice"></i>Pizza Média
                    <ul>
                        <li class="row">
                            <label class="col col1-3" for="pizza-media-2">2 sabores</label>
                            <input class="col col1-3" type="radio" id="pizza-media-2" name="size" value="pizza-media-2">
                        </li>
                        <li class="row">
                            <label class="col col1-3" for="pizza-media-1">1 sabor</label>
                            <input class="col col1-3" type="radio" id="pizza-media-1" name="size" value="pizza-media-1">
                        </li>
                    </ul>
                </li>
                <li class="pizza-styles">
                    <i class="fas fa-pizza-slice"></i>Pizza Pequena
                    <ul>
                        <li class="row">
                            <label class="col col1-3" for="pizza-pequena-2">2 sabores</label>
                            <input class="col col1-3" type="radio" id="pizza-pequena-2" name="size"
                                value="pizza-pequena-2">
                        </li>
                        <li class="row">
                            <label class="col col1-3" for="pizza-pequena-1">1 sabor</label>
                            <input class="col col1-3" type="radio" id="pizza-pequena-1" name="size"
                                value="pizza-pequena-1">
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="pizza-categories">
                <h3 class="pizza-categories-title">Salgados</h3>
            </div>

            <table class="pizza-table car-table">
                <thead>
                    <tr>
                        <th>Sabores</th>
                        <th>Pizza Grande</th>
                        <th>Pizza Média</th>
                        <th>Pizza Pequena</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for sabor_salgado in sabores_salgados %}
                    <tr>
                        <td>{{ sabor_salgado.nome_sabor }}</td>
                        <td>{{ sabor_salgado.preco_grande|money }}</td>
                        <td>{{ sabor_salgado.preco_medio|money }}</td>
                        <td>{{ sabor_salgado.preco_pequeno|money }}</td>
                        <td><input class="check" type="checkbox" name="sabor-{{ sabor_salgado.nome_sabor }}"
                                value="{{ sabor_salgado.id }}"></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="pizza-categories pizza-categories-margin-top">
                <h3 class="pizza-categories-title">Doces</h3>
            </div>

            <table class="pizza-table car-table">
                <thead>
                    <tr>
                        <th>Sabores</th>
                        <th>Pizza Grande</th>
                        <th>Pizza Média</th>
                        <th>Pizza Pequena</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for sabor_doce in sabores_doces %}
                    <tr>
                        <td>{{ sabor_doce.nome_sabor }}</td>
                        <td>{{ sabor_doce.preco_grande|money }}</td>
                        <td>{{ sabor_doce.preco_medio|money }}</td>
                        <td>{{ sabor_doce.preco_pequeno|money }}</td>
                        <td><input type="checkbox" name="sabor-{{ sabor_doce.nome_sabor }}" value="{{ sabor_doce.id }}">
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <input class="submit-button" type="submit" value="Fazer Pedido">

        </form>


    </section>
</main>

{% endblock %}

pedido/templates/pedido/meus_pedidos.html
{% extends 'base.html' %}
{% load myfilter %}

{% block title %}Meus Pedidos{% endblock %}

{% block content %}
<main>
    <section class="main-section">
        <h2 class="main-section-title">Pedidos Feitos</h2>
        {% if pedidos %}
        <table class="car-table">
            <thead>
                <tr>
                    <th>Sabores</th>
                    <th>Endereço</th>
                    <th>Data</th>
                    <th>Status</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr>
                    <td>
                        {% for item in pedido.itempedido_set.all %}
                        {{ item.sabor }};
                        {% endfor %}
                    </td>
                    <td>Rua {{ pedido.endereco }}</td>
                    <td>{{ pedido.data }}</td>
                    <td>{{ pedido.get_status_display }}</td>
                    <td>{{ pedido.total|money }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Você ainda não fez pedidos.</p>
        {% endif %}

    </section>
</main>
{% endblock %}